live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[scrolling]
history = 100000

[window]
dynamic_title =  false
title = "Terminal"
